/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Инфраструктура участка и состав поездов с исходным расписанием */
        get: operations["get_world_api_world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущее состояние участка */
        get: operations["get_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Действующий план движения */
        get: operations["get_plan_api_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Индекс эффективности участка 0–100 и факторы, которые тянут его вниз */
        get: operations["get_index_api_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал событий текущего прогона */
        get: operations["get_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenarios */
        get: operations["get_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Старт, пауза, ускорение ×1…×100, шаг, сброс */
        post: operations["sim_control_api_sim_control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Загрузить сценарий и/или сгенерировать мир с новым seed */
        post: operations["sim_load_api_sim_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Веса, пороги, параметры */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Формат сообщений WebSocket /api/stream на живых данных */
        get: operations["stream_schema_api_stream_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BagdarConfig */
        BagdarConfig: {
            /**
             * Mode
             * @default mainline
             * @enum {string}
             */
            mode: "mainline" | "lrt";
            /**
             * Pte Strict
             * @default true
             */
            pte_strict: boolean;
            /**
             * @default {
             *       "weights": {
             *         "conflicts": 0.1,
             *         "punctuality": 0.25,
             *         "resource_idle": 0.15,
             *         "throughput": 0.3,
             *         "track_load": 0.2
             *       },
             *       "thresholds": {
             *         "normal": 75,
             *         "warning": 50
             *       },
             *       "punctuality_max_delay_min": 30,
             *       "conflicts_max": 10
             *     }
             */
            index: components["schemas"]["IndexConfig"];
            /** Priority */
            priority?: {
                [key: string]: components["schemas"]["PriorityEntry"];
            };
            /**
             * @default {
             *       "c_stop": 0.5,
             *       "c_energy": 0.1,
             *       "c_idle": 2,
             *       "c_change": 15
             *     }
             */
            cost: components["schemas"]["CostConfig"];
            /**
             * @default {
             *       "horizon_min": 180,
             *       "freeze_min": 5,
             *       "time_limit_s": 2,
             *       "fallback": "greedy"
             *     }
             */
            solver: components["schemas"]["SolverConfig"];
            /**
             * @default {
             *       "dt_s": 1,
             *       "start_time": "06:00",
             *       "tau_cross_s": 90,
             *       "headway_s": 300,
             *       "headway_arr_s": 180,
             *       "throat_s": 90,
             *       "approach_s": 90,
             *       "clear_s": 60,
             *       "prep_s": 600,
             *       "terminate_s": 600,
             *       "min_stop_s": 30,
             *       "recovery_margin": 0.07,
             *       "max_wait_s": 3600,
             *       "dwell_jitter_prob": 0.25,
             *       "dwell_jitter_max_s": 90,
             *       "origin_delay_prob": 0.12,
             *       "origin_delay_max_s": 300,
             *       "broadcast_hz": 10
             *     }
             */
            sim: components["schemas"]["SimConfig"];
        };
        /** ControlIn */
        ControlIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "start" | "pause" | "speed" | "step" | "reset";
            /** Speed */
            speed?: number | null;
            /**
             * Step S
             * @description Шаг в секундах модели (по умолчанию 60)
             */
            step_s?: number | null;
        };
        /** ControlOut */
        ControlOut: {
            /** Running */
            running: boolean;
            /** Speed */
            speed: number;
            /** T */
            t: number;
            /** Run Id */
            run_id: string;
        };
        /** CostConfig */
        CostConfig: {
            /**
             * C Stop
             * @default 0.5
             */
            c_stop: number;
            /**
             * C Energy
             * @default 0.1
             */
            c_energy: number;
            /**
             * C Idle
             * @default 2
             */
            c_idle: number;
            /**
             * C Change
             * @default 15
             */
            c_change: number;
        };
        /** EventOut */
        EventOut: {
            /** Seq */
            seq: number;
            /** T */
            t: number;
            /** Kind */
            kind: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "debug" | "info" | "warn" | "critical";
            /** Message */
            message: string;
            /** Train Id */
            train_id: string | null;
            /** Station Id */
            station_id: string | null;
            /** Section Id */
            section_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** EventsMsg */
        EventsMsg: {
            /**
             * Type
             * @default events
             * @constant
             */
            type: "events";
            /**
             * Reset
             * @description true — заменить ленту, false — дописать
             */
            reset: boolean;
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** EventsOut */
        EventsOut: {
            /** Run Id */
            run_id: string;
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** GenerationOut */
        GenerationOut: {
            /** Trains Total */
            trains_total: number;
            /** Dropped */
            dropped: string[];
            /** Build Ms */
            build_ms: number;
            /** Validated */
            validated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** World Loaded */
            world_loaded: boolean;
        };
        /** HelloMsg */
        HelloMsg: {
            /**
             * Type
             * @default hello
             * @constant
             */
            type: "hello";
            /** Protocol */
            protocol: number;
            /** Run Id */
            run_id: string;
            /** World Version */
            world_version: number;
        };
        /** IndexConfig */
        IndexConfig: {
            /**
             * @default {
             *       "throughput": 0.3,
             *       "punctuality": 0.25,
             *       "track_load": 0.2,
             *       "resource_idle": 0.15,
             *       "conflicts": 0.1
             *     }
             */
            weights: components["schemas"]["IndexWeights"];
            /**
             * @default {
             *       "normal": 75,
             *       "warning": 50
             *     }
             */
            thresholds: components["schemas"]["IndexThresholds"];
            /**
             * Punctuality Max Delay Min
             * @default 30
             */
            punctuality_max_delay_min: number;
            /**
             * Conflicts Max
             * @default 10
             */
            conflicts_max: number;
        };
        /** IndexFactorOut */
        IndexFactorOut: {
            /**
             * Key
             * @enum {string}
             */
            key: "throughput" | "punctuality" | "track_load" | "resource_idle" | "conflicts";
            /** Label */
            label: string;
            /**
             * Score
             * @description Оценка фактора от 0 до 1
             */
            score: number;
            /**
             * Weight
             * @description Нормированный вес (сумма весов = 1)
             */
            weight: number;
            /**
             * Points
             * @description Вклад в индекс, баллы из 100
             */
            points: number;
            /**
             * Loss
             * @description Сколько баллов фактор недобирает
             */
            loss: number;
            /** Detail */
            detail: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** IndexOut */
        IndexOut: {
            /** T */
            t: number;
            /** Value */
            value: number;
            /**
             * Level
             * @enum {string}
             */
            level: "normal" | "warning" | "critical";
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
            /** Factors */
            factors: components["schemas"]["IndexFactorOut"][];
            /**
             * Drag
             * @description Факторы, которые сильнее всего тянут индекс вниз
             */
            drag: string[];
        };
        /** IndexThresholds */
        IndexThresholds: {
            /**
             * Normal
             * @default 75
             */
            normal: number;
            /**
             * Warning
             * @default 50
             */
            warning: number;
        };
        /** IndexWeights */
        IndexWeights: {
            /**
             * Throughput
             * @default 0.3
             */
            throughput: number;
            /**
             * Punctuality
             * @default 0.25
             */
            punctuality: number;
            /**
             * Track Load
             * @default 0.2
             */
            track_load: number;
            /**
             * Resource Idle
             * @default 0.15
             */
            resource_idle: number;
            /**
             * Conflicts
             * @default 0.1
             */
            conflicts: number;
        };
        /** LoadIn */
        LoadIn: {
            /** Scenario Id */
            scenario_id?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** LoadOut */
        LoadOut: {
            /** World Version */
            world_version: number;
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Seed */
            seed: number;
            /** Trains Total */
            trains_total: number;
            /** Load Ms */
            load_ms: number;
        };
        /** MetricsOut */
        MetricsOut: {
            /** Active Trains */
            active_trains: number;
            /** Finished Trains */
            finished_trains: number;
            /** Avg Delay S */
            avg_delay_s: number;
            /** Max Delay S */
            max_delay_s: number;
            /** On Time Share */
            on_time_share: number;
            /** Waiting Trains */
            waiting_trains: number;
            /** Unplanned Stops */
            unplanned_stops: number;
            /** Stop Energy Kwh */
            stop_energy_kwh: number;
        };
        /** PerfOut */
        PerfOut: {
            /** Step Us */
            step_us: number;
            /** Tick Ms */
            tick_ms: number;
            /** Steps Per S */
            steps_per_s: number;
            /** Load Ms */
            load_ms: number;
        };
        /** PlanLegOut */
        PlanLegOut: {
            /** Train Id */
            train_id: string;
            /** K */
            k: number;
            /** Section Id */
            section_id: string;
            /** From Id */
            from_id: string;
            /** To Id */
            to_id: string;
            /** Direction */
            direction: number;
            /** Dep */
            dep: number;
            /** Arr */
            arr: number;
            /** Track Id */
            track_id: string;
            /** Stop */
            stop: boolean;
        };
        /** PlanOut */
        PlanOut: {
            /** Version */
            version: number;
            /** Created At */
            created_at: number;
            /** Solver */
            solver: string;
            /**
             * Status
             * @enum {string}
             */
            status: "feasible" | "delayed" | "infeasible";
            /** Compute Ms */
            compute_ms: number;
            /** Notes */
            notes: string[];
            /** Cost */
            cost: {
                [key: string]: number;
            };
            /** Legs */
            legs: components["schemas"]["PlanLegOut"][];
        };
        /** PriorityEntry */
        PriorityEntry: {
            /** Weight */
            weight: number;
            /** Tolerance Min */
            tolerance_min: number;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Mode */
            mode: string;
            /** Seed */
            seed: number;
            /** Start Time */
            start_time: string;
            /** Difficulty */
            difficulty: number;
            /** Wave */
            wave: number;
            /** Disruptions */
            disruptions: number;
        };
        /** ScheduleStopOut */
        ScheduleStopOut: {
            /** Station Id */
            station_id: string;
            /** Arr */
            arr: number | null;
            /** Dep */
            dep: number | null;
            /** Stop */
            stop: boolean;
            /** Dwell S */
            dwell_s: number | null;
            /** Track Id */
            track_id: string;
        };
        /** SectionOut */
        SectionOut: {
            /** Id */
            id: string;
            /** A */
            a: string;
            /** B */
            b: string;
            /** Length Km */
            length_km: number;
            /**
             * Tracks
             * @description 1 — однопутный, 2 — двухпутный
             */
            tracks: number;
            /**
             * Signalling
             * @enum {string}
             */
            signalling: "AB" | "PAB";
            /** Blocks */
            blocks: number;
            /** Speed Limit Kmh */
            speed_limit_kmh: number;
            /**
             * Gradient Permille
             * @description Уклон в направлении a→b, ‰; плюс — подъём
             */
            gradient_permille: number;
            /** No Stop Uphill */
            no_stop_uphill: boolean;
            /** Electrified */
            electrified: boolean;
            /** Throat A */
            throat_a: string;
            /** Throat B */
            throat_b: string;
        };
        /** SectionStateOut */
        SectionStateOut: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "restricted" | "closed";
            /** Single */
            single: boolean;
            /** Restriction Kmh */
            restriction_kmh: number | null;
            /** Occupants */
            occupants: string[];
            /** Dir */
            dir: number;
        };
        /** SignalOut */
        SignalOut: {
            /** Id */
            id: string;
            /** Section Id */
            section_id: string;
            /** Station Id */
            station_id: string;
            /** Direction */
            direction: number;
        };
        /** SignalStateOut */
        SignalStateOut: {
            /** Id */
            id: string;
            /**
             * State
             * @enum {string}
             */
            state: "open" | "closed" | "fault";
        };
        /** SimConfig */
        SimConfig: {
            /**
             * Dt S
             * @default 1
             */
            dt_s: number;
            /**
             * Start Time
             * @default 06:00
             */
            start_time: string;
            /**
             * Tau Cross S
             * @default 90
             */
            tau_cross_s: number;
            /**
             * Headway S
             * @default 300
             */
            headway_s: number;
            /**
             * Headway Arr S
             * @default 180
             */
            headway_arr_s: number;
            /**
             * Throat S
             * @default 90
             */
            throat_s: number;
            /**
             * Approach S
             * @default 90
             */
            approach_s: number;
            /**
             * Clear S
             * @default 60
             */
            clear_s: number;
            /**
             * Prep S
             * @default 600
             */
            prep_s: number;
            /**
             * Terminate S
             * @default 600
             */
            terminate_s: number;
            /**
             * Min Stop S
             * @default 30
             */
            min_stop_s: number;
            /**
             * Recovery Margin
             * @default 0.07
             */
            recovery_margin: number;
            /**
             * Max Wait S
             * @default 3600
             */
            max_wait_s: number;
            /**
             * Dwell Jitter Prob
             * @default 0.25
             */
            dwell_jitter_prob: number;
            /**
             * Dwell Jitter Max S
             * @default 90
             */
            dwell_jitter_max_s: number;
            /**
             * Origin Delay Prob
             * @default 0.12
             */
            origin_delay_prob: number;
            /**
             * Origin Delay Max S
             * @default 300
             */
            origin_delay_max_s: number;
            /**
             * Broadcast Hz
             * @default 10
             */
            broadcast_hz: number;
        };
        /** SolverConfig */
        SolverConfig: {
            /**
             * Horizon Min
             * @default 180
             */
            horizon_min: number;
            /**
             * Freeze Min
             * @default 5
             */
            freeze_min: number;
            /**
             * Time Limit S
             * @default 2
             */
            time_limit_s: number;
            /**
             * Fallback
             * @default greedy
             * @constant
             */
            fallback: "greedy";
        };
        /** StateOut */
        StateOut: {
            /**
             * Type
             * @default state
             * @constant
             */
            type: "state";
            /** Run Id */
            run_id: string;
            /** World Version */
            world_version: number;
            /** Seq */
            seq: number;
            /** Tick */
            tick: number;
            /** T */
            t: number;
            /** Running */
            running: boolean;
            /** Speed */
            speed: number;
            /** Trains */
            trains: components["schemas"]["TrainStateOut"][];
            /** Sections */
            sections: components["schemas"]["SectionStateOut"][];
            /** Tracks */
            tracks: components["schemas"]["TrackStateOut"][];
            /** Throats */
            throats: components["schemas"]["ThroatStateOut"][];
            /** Signals */
            signals: components["schemas"]["SignalStateOut"][];
            metrics: components["schemas"]["MetricsOut"];
            perf: components["schemas"]["PerfOut"];
        };
        /** StationOut */
        StationOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "terminal" | "station" | "loop" | "junction";
            /** Km */
            km: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Zone Id */
            zone_id: string;
            /** Crew Change */
            crew_change: boolean;
            /** Tracks */
            tracks: components["schemas"]["TrackOut"][];
        };
        /**
         * StreamSchema
         * @description Документация WebSocket /api/stream. Сервер шлёт hello, затем world (если версия
         *     мира у клиента устарела), events и state; дальше state с частотой broadcast_hz и
         *     events по мере появления. Переподключение: /api/stream?world_version=N&last_seq=M&run_id=R.
         */
        StreamSchema: {
            hello: components["schemas"]["HelloMsg"];
            world: components["schemas"]["WorldMsg"];
            events: components["schemas"]["EventsMsg"];
            state: components["schemas"]["StateOut"];
        };
        /** SwitchOut */
        SwitchOut: {
            /** Id */
            id: string;
            /** Station Id */
            station_id: string;
            /** Track Id */
            track_id: string;
            /** Number */
            number: number;
        };
        /** ThroatStateOut */
        ThroatStateOut: {
            /** Id */
            id: string;
            /** Holder */
            holder: string | null;
        };
        /** TrackOut */
        TrackOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Length M */
            length_m: number;
            /** Is Main */
            is_main: boolean;
        };
        /** TrackStateOut */
        TrackStateOut: {
            /** Id */
            id: string;
            /** Occupant */
            occupant: string | null;
            /** Reserved */
            reserved: string | null;
            /** Available */
            available: boolean;
        };
        /** TrainClassOut */
        TrainClassOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Pte Rank */
            pte_rank: number;
            /** Weight */
            weight: number;
            /** Tolerance Min */
            tolerance_min: number;
        };
        /** TrainStateOut */
        TrainStateOut: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "station" | "section" | "finished";
            /**
             * Display
             * @enum {string}
             */
            display: "ready" | "dwell" | "held" | "terminated" | "running" | "braking" | "stopped" | "pending" | "finished";
            /** K */
            k: number;
            /** Station Id */
            station_id: string | null;
            /** Track Id */
            track_id: string | null;
            /** Section Id */
            section_id: string | null;
            /**
             * Progress
             * @description Положение на перегоне 0..1 от станции a к b
             */
            progress: number | null;
            /** V Kmh */
            v_kmh: number;
            /** V Target Kmh */
            v_target_kmh: number;
            /** Delay S */
            delay_s: number;
            /** Wait Reason */
            wait_reason: string | null;
            /** Dest Track */
            dest_track: string | null;
            /** Through */
            through: boolean;
            /** Next Station Id */
            next_station_id: string | null;
            /** Crew Left S */
            crew_left_s: number;
            /** Stops */
            stops: number;
            /** Unplanned Stops */
            unplanned_stops: number;
            /** Stop Energy Kwh */
            stop_energy_kwh: number;
        };
        /** TrainStaticOut */
        TrainStaticOut: {
            /** Id */
            id: string;
            /** Number */
            number: string;
            /** Cls */
            cls: string;
            /** Cls Label */
            cls_label: string;
            /**
             * Pte Rank
             * @description 0 — внеочередной, 1..5 — очерёдность по ПТЭ
             */
            pte_rank: number;
            /** Direction */
            direction: number;
            /** Length M */
            length_m: number;
            /** Mass T */
            mass_t: number;
            /** Passengers */
            passengers: number;
            /** Cargo */
            cargo: string[];
            /**
             * Traction
             * @enum {string}
             */
            traction: "electric" | "diesel";
            /** Vmax Kmh */
            vmax_kmh: number;
            /** Loco Id */
            loco_id: string;
            /** Crew Id */
            crew_id: string;
            /** Crew Shift End */
            crew_shift_end: number | null;
            /** Route */
            route: string[];
            /** Sections */
            sections: string[];
            /** Suburban */
            suburban: boolean;
            /** Transfer */
            transfer: boolean;
            /** Schedule */
            schedule: components["schemas"]["ScheduleStopOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorldMsg */
        WorldMsg: {
            /**
             * Type
             * @default world
             * @constant
             */
            type: "world";
            world: components["schemas"]["WorldOut"];
        };
        /** WorldOut */
        WorldOut: {
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Seed */
            seed: number;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Scenario Id */
            scenario_id: string;
            /** Start Time */
            start_time: number;
            /** Date */
            date: string;
            /** Tz */
            tz: string;
            /** Zones */
            zones: components["schemas"]["ZoneOut"][];
            /** Stations */
            stations: components["schemas"]["StationOut"][];
            /** Sections */
            sections: components["schemas"]["SectionOut"][];
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
            /** Switches */
            switches: components["schemas"]["SwitchOut"][];
            /** Trains */
            trains: components["schemas"]["TrainStaticOut"][];
            /** Classes */
            classes: components["schemas"]["TrainClassOut"][];
            generation: components["schemas"]["GenerationOut"];
        };
        /** ZoneOut */
        ZoneOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Station Ids */
            station_ids: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_world_api_world_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldOut"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateOut"];
                };
            };
        };
    };
    get_plan_api_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
        };
    };
    get_index_api_index_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexOut"];
                };
            };
        };
    };
    get_events_api_events_get: {
        parameters: {
            query?: {
                since?: number;
                limit?: number;
                min_severity?: "debug" | "info" | "warn" | "critical";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    sim_control_api_sim_control_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sim_load_api_sim_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BagdarConfig"];
                };
            };
        };
    };
    stream_schema_api_stream_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamSchema"];
                };
            };
        };
    };
}
